name: Dependency graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  submit-dependencies:
    name: Submit dependency graph
    runs-on: [self-hosted, jamf-ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: corretto
          cache: gradle
      - name: Submit Dependency Snapshot
        uses: gradle/actions/dependency-submission@v4
